version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: pinit_db
    environment:
      POSTGRES_DB: pinit_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: pinit_backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/pinit_db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CLERK_ISSUER_URI=${CLERK_ISSUER_URI}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
